CREATE TABLE "config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"config" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "paths" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"source" text,
	"source_fingerprint" text,
	"source_on_demand" boolean,
	"source_on_demand_start_timeout" text,
	"source_on_demand_close_after" text,
	"max_readers" text,
	"srt_read_passphrase" text,
	"fallback" text,
	"record" boolean,
	"record_path" text,
	"record_format" text,
	"record_part_duration" text,
	"record_segment_duration" text,
	"record_delete_after" text,
	"override_publisher" boolean,
	"srt_publish_passphrase" text,
	"rtsp_transport" text,
	"rtsp_any_port" boolean,
	"rtsp_range_type" text,
	"rtsp_range_start" text,
	"source_redirect" text,
	"rpi_camera_cam_id" text,
	"rpi_camera_width" text,
	"rpi_camera_height" text,
	"rpi_camera_h_flip" boolean,
	"rpi_camera_v_flip" boolean,
	"rpi_camera_brightness" text,
	"rpi_camera_contrast" text,
	"rpi_camera_saturation" text,
	"rpi_camera_sharpness" text,
	"rpi_camera_exposure" text,
	"rpi_camera_awb" text,
	"rpi_camera_awb_gains" text,
	"rpi_camera_denoise" text,
	"rpi_camera_shutter" text,
	"rpi_camera_metering" text,
	"rpi_camera_gain" text,
	"rpi_camera_ev" text,
	"rpi_camera_roi" text,
	"rpi_camera_hdr" boolean,
	"rpi_camera_tuning_file" text,
	"rpi_camera_mode" text,
	"rpi_camera_fps" text,
	"rpi_camera_af_mode" text,
	"rpi_camera_af_range" text,
	"rpi_camera_af_speed" text,
	"rpi_camera_lens_position" text,
	"rpi_camera_af_window" text,
	"rpi_camera_flicker_period" text,
	"rpi_camera_text_overlay_enable" boolean,
	"rpi_camera_text_overlay" text,
	"rpi_camera_codec" text,
	"rpi_camera_idr_period" text,
	"rpi_camera_bitrate" text,
	"rpi_camera_profile" text,
	"rpi_camera_level" text,
	"run_on_init" text,
	"run_on_init_restart" boolean,
	"run_on_demand" text,
	"run_on_demand_restart" boolean,
	"run_on_demand_start_timeout" text,
	"run_on_demand_close_after" text,
	"run_on_undemand" text,
	"run_on_ready" text,
	"run_on_ready_restart" boolean,
	"run_on_not_ready" text,
	"run_on_read" text,
	"run_on_read_restart" boolean,
	"run_on_unread" text,
	"run_on_record_segment_create" text,
	"run_on_record_segment_complete" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
