services:
  mediamtx:
    image: bluenviron/mediamtx:1.10.0
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSx  P
      - "5555:5555" # udp stream
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC
      - "9997:9997" # API
      - "9998:9998" # Metrics
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
