services:
  mediamtx:
    image: bluenviron/mediamtx:1.10.0
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSx  P
      - "5555:5555" # udp stream
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC
      - "9997:9997" # API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    # environment:
    #   - MTX_PROTOCOLS=tcp

  # rtsp-simple-server:
  #   image: aler9/rtsp-simple-server
  #   container_name: rtsp-simple-server
  #   restart: unless-stopped
  #   ports:
  #     - "8555:8554" # RTSP
  #   volumes:
  #     - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
